name: Continuous Integration

on:
  push:
    branches:
      - main
      - wip
  pull_request:

jobs:
  stable-ci:
    name: "Build & Test (on Stable Rust)"
    runs-on: ubuntu-latest
    env:
      STABLE_FEATURES: "cortex-m,std"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build shared-bus with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: "--features ${{ env.STABLE_FEATURES }}"
      - name: Test shared-bus with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: "--features ${{ env.STABLE_FEATURES }}"
  nightly-ci:
    name: "Build & Test (on Nightly Rust)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build shared-bus with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
      - name: Test shared-bus with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
